before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go vet
builds:
  - goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/brittonhayes/armactl/cmd/armactl/version.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    main: "./cmd/armactl"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^images:"
      - "^_examples:"

brews:
  - # Name template of the recipe
    # Default to project name
    name: armactl

    # GOARM to specify which 32-bit arm version to use if there are multiple versions
    # from the build section. Brew formulas support atm only one 32-bit version.
    # Default is 6 for all artifacts or each id if there a multiple versions.
    goarm: "6"

    # GitHub/GitLab repository to push the formula to
    # Gitea is not supported yet, but the support coming
    tap:
      owner: brittonhayes
      name: armactl

    url_template: "https://github.com/brittonhayes/armactl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/brittonhayes/armactl"

    # Your app's description.
    # Default is empty.
    description: "CLI for managing ARMA3 dedicated servers."

    license: "MIT"
