before:
  hooks:
    - go mod tidy
builds:
  - id: "armactl"
    main: "./cmd/armactl"
    binary: "armactl"
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/brittonhayes/armactl/cmd/armactl/version.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

brews:
  - name: armactl
    goarm: "6"
    homepage: "https://github.com/brittonhayes/armactl"
    description: "CLI for managing ARMA3 dedicated servers."
    license: "MIT"
    url_template: "https://github.com/brittonhayes/armactl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    tap:
      owner: brittonhayes
      name: armactl
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com


scoop:
    url_template: "https://github.com/brittonhayes/armactl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    bucket:
      owner: brittonhayes
      name: armactl
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^images:"
      - "^_examples:"