# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Armactl < Formula
  desc "CLI for managing ARMA3 dedicated servers."
  homepage "https://github.com/brittonhayes/armactl"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.2.0/armactl_0.2.0_darwin_amd64.tar.gz"
      sha256 "7fba5e17395fff966b7f80d8778201c7d37f2f9f6faf8d476aa89644b9d4d8e3"

      def install
        bin.install "armactl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.2.0/armactl_0.2.0_darwin_arm64.tar.gz"
      sha256 "cfa2c48d1effaf2216289c708557fc22959e0e8bbdfc9895d1c343e2d4741f55"

      def install
        bin.install "armactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.2.0/armactl_0.2.0_linux_arm64.tar.gz"
      sha256 "faac241e835de49842b9d0785d99d2115613d73399b20e81e15ed3d4a82471ad"

      def install
        bin.install "armactl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.2.0/armactl_0.2.0_linux_amd64.tar.gz"
      sha256 "f7ae0be827bdb8ea5cf2344be86053f25e7537b903e629cf4a91b4111c285750"

      def install
        bin.install "armactl"
      end
    end
  end
end
