# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Armactl < Formula
  desc "CLI for managing ARMA3 dedicated servers."
  homepage "https://github.com/brittonhayes/armactl"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.4.0/armactl_0.4.0_darwin_arm64.tar.gz"
      sha256 "a4c64a430b515140a011b91848444ffbc70a2169ae15a870a406a1d77bdf2a50"

      def install
        bin.install "armactl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.4.0/armactl_0.4.0_darwin_amd64.tar.gz"
      sha256 "5d20926ad7eabafc84e3d76429f4ca24dfb91afb06f6f1766085597c37967c22"

      def install
        bin.install "armactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.4.0/armactl_0.4.0_linux_amd64.tar.gz"
      sha256 "da32324881473351ba5533f5f4e595a82a305cf37b7a00943e3a87c0f1031fed"

      def install
        bin.install "armactl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brittonhayes/armactl/releases/download/v0.4.0/armactl_0.4.0_linux_arm64.tar.gz"
      sha256 "168bff5b1c9279f53a1067f76f52253de3b8015a722d4eb8e9a717c4dc0413a9"

      def install
        bin.install "armactl"
      end
    end
  end
end
